theme: jekyll-theme-minimal
title: M.Mojahidul Islam's Website
description: Keep an eye for latest updates!
lsi: false
safe: true
source: personal_website
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge